# Generated by Django 4.0.6 on 2022-07-11 10:14

import account.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_portaluser_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='portaluser',
            managers=[
                ('objects', account.models.UserManager()),
            ],
        ),
    ]
