# Generated by Django 4.0.6 on 2022-07-12 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_portaluser_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='portaluser',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='Is Admin'),
        ),
        migrations.AddField(
            model_name='portaluser',
            name='is_child',
            field=models.BooleanField(default=False, verbose_name='Is Child'),
        ),
        migrations.AddField(
            model_name='portaluser',
            name='is_guardian',
            field=models.BooleanField(default=False, verbose_name='Is Guardian'),
        ),
    ]
