# Generated by Django 4.0.6 on 2022-07-12 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_portaluser_is_admin_portaluser_is_child_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portaluser',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='portaluser',
            name='is_child',
        ),
        migrations.RemoveField(
            model_name='portaluser',
            name='is_guardian',
        ),
    ]
