# Generated by Django 4.0.6 on 2022-07-12 07:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_child'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='child',
            name='guardian',
        ),
        migrations.AddField(
            model_name='child',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='guardian',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='guardian', to=settings.AUTH_USER_MODEL),
        ),
    ]
