# Generated by Django 4.0.6 on 2022-07-12 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_remove_child_guardian_child_name_alter_guardian_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guardian',
            old_name='user',
            new_name='child',
        ),
    ]
