# Generated by Django 4.0.6 on 2022-07-12 08:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_rename_user_guardian_child'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guardian',
            name='child',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='child', to=settings.AUTH_USER_MODEL),
        ),
    ]
