# Generated by Django 4.0.6 on 2022-07-12 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_alter_guardian_child'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Child',
        ),
        migrations.RenameField(
            model_name='guardian',
            old_name='child',
            new_name='user',
        ),
    ]
