# Generated by Django 4.0.6 on 2022-07-12 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_guardian_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='guardian',
            name='email',
            field=models.EmailField(default=2, max_length=254),
            preserve_default=False,
        ),
    ]
