# Generated by Django 4.0.6 on 2022-07-13 08:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_remove_guardian_user_delete_child_delete_guardian'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portaluser',
            name='username',
            field=models.CharField(max_length=10, null=True, unique=True, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.')]),
        ),
    ]
