# Generated by Django 4.0.6 on 2022-07-14 04:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_alter_portaluser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portaluser',
            name='username',
            field=models.CharField(max_length=100, null=True, unique=True, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.')]),
        ),
    ]
